# Symlink this file to /etc/sensors.d/
# cd /etc/sensors.d
# sudo ln -s $HOME/Projects/config/ignored_sensors.conf

# Ref: https://github.com/lm-sensors/lm-sensors/issues/368
# Kingston NV2 M.2 SSD causes warnings as follows while running sensors.
# ERROR: Can't get value of subfeature temp3_min: I/O error
# ERROR: Can't get value of subfeature temp3_max: I/O error

chip "nvme-pci-*"
    ignore temp3

chip "applesmc-*"
    ignore temp1
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7
    ignore temp8
    ignore temp9
    ignore temp10
    ignore temp11
    ignore temp12
    ignore temp13
    ignore temp14
    ignore temp15
    ignore temp16
    ignore temp17
    ignore temp18
    ignore temp19
    ignore temp20
    ignore temp21
    ignore temp22
    ignore temp23
    ignore temp24
    ignore temp25
    ignore temp26
    ignore temp27
    ignore temp28
    ignore temp29
    ignore temp30
    ignore temp31
    ignore temp32
    ignore temp33
    ignore temp34
    ignore temp35
    ignore temp36
    ignore temp37
    ignore temp38
    ignore temp39
    ignore temp40
    ignore temp41
    ignore temp42
    ignore temp43
    ignore temp44
    ignore temp45
    ignore temp46
    ignore temp47
    ignore temp48
    ignore temp49
    ignore temp50
    ignore temp51
    ignore temp52
    ignore temp53
    ignore temp54
    ignore temp55
    ignore temp56
    ignore temp57
    ignore temp58
    ignore temp59
    ignore temp60
    ignore temp61
    ignore temp62
    ignore temp63
    ignore temp64
    ignore temp65
    ignore temp66
    ignore temp67
    ignore temp68
