# Symlink this file to /etc/sensors.d/
# cd /etc/sensors.d
# sudo ln -s $HOME/Projects/config/nv2_ssd.conf

# Ref: https://github.com/lm-sensors/lm-sensors/issues/368
# Kingston NV2 M.2 SSD causes warnings as follows while running sensors.
# ERROR: Can't get value of subfeature temp3_min: I/O error
# ERROR: Can't get value of subfeature temp3_max: I/O error

chip "nvme-pci-*"
    ignore temp3
